os:
  - linux
  - osx

language: cpp

compiler:
  - gcc
  - clang

env:
  native:
    - CROSS_COMPILE32=0
    - FEATURE_RENDERER2=1
    - RENDERER_DYNAMIC=1
    - BUNDLED_LIBS=1
    - BUNDLED_SDL=1
    - BUNDLED_JPEG=1
    - BUNDLED_LUA=1
    - BUNDLED_OGG=1
    - BUNDLED_CURL=1

before_install:
  - echo 'deb http://archive.ubuntu.com/ubuntu trusty main' | sudo tee /etc/apt/sources.list.d/ubuntu-trusty.list
  - sudo apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 40976EAF437D05B5
  - sudo apt-get update -qq
  - sudo apt-get install -q -t precise pkg-config nasm libgl1-mesa-dev libasound2-dev pulseaudio m4
  - sudo apt-get install -q -t trusty automake

script:
  - ./easybuild.sh

branches:
  only:
    - develop
